export const UNIT_NAMES = [
  "1 Bn The Royal Irish Regiment",
  "1 Bn The Rifles",
  "2 Bn The Rifles",
  "3 Bn The Rifles",
  "4 Bn The Rifles",
  "1 Bn Welsh Guards",
  "1 Bn Scots Guards",
  "1 Bn Irish Guards",
  "1 Bn Grenadier Guards",
  "1 Bn Coldstream Guards",
  "2 Bn The Parachute Regiment",
  "3 Bn The Parachute Regiment",
  "1 Bn The Royal Regiment of Fusiliers",
  "2 Bn The Royal Regiment of Fusiliers",
  "1 Bn The Mercian Regiment",
  "2 Bn The Mercian Regiment",
  "3 Bn The Mercian Regiment",
  "4 Bn The Mercian Regiment",
  "1 Bn The Royal Anglian Regiment",
  "2 Bn The Royal Anglian Regiment",
  "3 Bn The Royal Anglian Regiment",
  "1 Bn The Yorkshire Regiment",
  "2 Bn The Yorkshire Regiment",
  "4 Bn The Yorkshire Regiment",
  "1 Bn The Duke of Lancaster's Regiment",
  "2 Bn The Duke of Lancaster's Regiment",
  "4 Bn The Duke of Lancaster's Regiment",
  "1 Bn The Princess of Wales's Royal Regiment",
  "2 Bn The Princess of Wales's Royal Regiment",
  "4 Bn The Princess of Wales's Royal Regiment",
  "1 Bn The Royal Welsh",
  "2 Bn The Royal Welsh",
  "3 Bn The Royal Welsh",
  "1 Bn The Royal Regiment of Scotland",
  "2 Bn The Royal Regiment of Scotland",
  "3 Bn The Royal Regiment of Scotland",
  "4 Bn The Royal Regiment of Scotland",
  "5 Bn The Royal Regiment of Scotland",
  "6 Bn The Royal Regiment of Scotland",
  "7 Bn The Royal Regiment of Scotland",
  "1st Battalion, The Royal Gurkha Rifles",
  "2nd Battalion, The Royal Gurkha Rifles",
  "Other",
] as const;
