-- AlterTable
ALTER TABLE `NewsPost` ADD COLUMN `pdfPath` VARCHAR(191);
ALTER TABLE `NewsPost` ADD COLUMN `pdfOriginalName` VARCHAR(191);
ALTER TABLE `NewsPost` ADD COLUMN `pdfMimeType` VARCHAR(191);
ALTER TABLE `NewsPost` ADD COLUMN `pdfFileSize` INTEGER;
